install: true  
addons:
  ssh_known_hosts: 
  - git.resinstaging.io
  - git.resin.io

script:  
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo -e $RESIN_DEPLOY_KEY > id_rsa
  - chmod 0600 id_rsa
  - ssh-add ./id_rsa
  - git remote add resin $RESIN_REMOTE
  - git push -f resin master