# base-image for golang on any machine using a template var
FROM resin/%%RESIN_MACHINE_NAME%%-golang:latest

ENV INITSYSTEM on

#Copy all the code into /go
COPY ./ $GOPATH/src/github.com/streamsets

#build all the Go source with gradle.
RUN cd $GOPATH/src/github.com/streamsets
RUN gradlew clean build

#tell our container to run the binary on start.
CMD ["./main"]